"""
AgentForge Demo
===============
This demo shows a complete agent defined entirely in Python —
no text config files, no giant prompts, just functions and formulas.

Run:  python demo/example_agent.py
"""
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from agentforge import (
    skill, rule,
    Pipeline, Phase, PipelineContext,
    AlignmentFormula, AlignmentDimension,
    keyword_avoid_scorer, length_scorer,
    Agent,
)

# ─────────────────────────────────────────────────────────────────────────────
# STEP 1: Define Skills (what the agent CAN do)
# ─────────────────────────────────────────────────────────────────────────────

@skill(name="understand_intent", tags=["cognition"], priority=10,
       description="Parse user intent from raw input")
def understand_intent(text: str) -> dict:
    """Classify the user's goal from their message."""
    text_lower = text.lower()
    if any(w in text_lower for w in ["calculate", "compute", "+", "-", "*", "/"]):
        intent = "math"
    elif any(w in text_lower for w in ["weather", "temperature", "rain"]):
        intent = "weather"
    elif any(w in text_lower for w in ["hello", "hi", "hey", "你好"]):
        intent = "greeting"
    else:
        intent = "general"
    return {"intent": intent, "original": text}


@skill(name="chain_of_thought", tags=["reasoning"], priority=8,
       description="Think step-by-step before answering")
def chain_of_thought(ctx: PipelineContext) -> str:
    """Generate a reasoning chain for the intent."""
    intent_data = ctx.get("understand_intent") or {}
    intent = intent_data.get("intent", "general")
    original = intent_data.get("original", "")

    steps = {
        "math":     f"Step 1: Identify numbers and operators in '{original}'\nStep 2: Apply arithmetic\nStep 3: Return result",
        "weather":  f"Step 1: Identify location in '{original}'\nStep 2: Query forecast\nStep 3: Summarize",
        "greeting": f"Step 1: Detect greeting\nStep 2: Respond warmly",
        "general":  f"Step 1: Parse topic\nStep 2: Retrieve knowledge\nStep 3: Compose answer",
    }
    return steps.get(intent, steps["general"])


@skill(name="format_output", tags=["output"], priority=5,
       description="Format the final response clearly")
def format_output(ctx: PipelineContext) -> str:
    """Take reasoning result and produce a clean response."""
    intent_data = ctx.get("understand_intent") or {}
    reasoning   = ctx.get("chain_of_thought") or ""
    intent      = intent_data.get("intent", "general")
    original    = intent_data.get("original", "")

    templates = {
        "greeting": f"👋 Hello! I'm AgentForge. How can I help you today?",
        "math":     f"🔢 Let me calculate that for you.\n\nReasoning:\n{reasoning}\n\nResult: [computed by your LLM]",
        "weather":  f"🌤️ Weather query detected.\n\nReasoning:\n{reasoning}\n\nResult: [fetched from weather API]",
        "general":  f"💬 Response to: '{original}'\n\nReasoning:\n{reasoning}\n\nAnswer: [generated by your LLM]",
    }
    return templates.get(intent, templates["general"])


# ─────────────────────────────────────────────────────────────────────────────
# STEP 2: Define Rules (what the agent MUST NOT do)
# ─────────────────────────────────────────────────────────────────────────────

HARMFUL_WORDS = ["hack", "bomb", "illegal", "steal", "weapon"]

@rule(name="no_harmful_input", severity="block", phase="pre",
      description="Block harmful or dangerous requests")
def no_harmful_input(text: str) -> tuple:
    text_lower = str(text).lower()
    hits = [w for w in HARMFUL_WORDS if w in text_lower]
    return (len(hits) == 0), f"Detected harmful keywords: {hits}"


@rule(name="output_not_empty", severity="error", phase="post",
      description="Ensure the agent always produces output")
def output_not_empty(output) -> tuple:
    not_empty = output is not None and len(str(output).strip()) > 0
    return not_empty, "Agent produced empty output"


# ─────────────────────────────────────────────────────────────────────────────
# STEP 3: Define Pipeline (HOW the agent thinks, in order)
# ─────────────────────────────────────────────────────────────────────────────

def intent_phase(ctx: PipelineContext):
    return understand_intent(str(ctx.input))

def reasoning_phase(ctx: PipelineContext):
    return chain_of_thought(ctx)

def output_phase(ctx: PipelineContext):
    return format_output(ctx)

def is_not_greeting(ctx: PipelineContext) -> bool:
    intent_data = ctx.get("understand_intent") or {}
    return intent_data.get("intent") != "greeting"

pipeline = Pipeline([
    Phase("understand_intent", intent_phase),
    Phase("chain_of_thought",  reasoning_phase, condition=is_not_greeting),
    Phase("format_output",     output_phase),
])


# ─────────────────────────────────────────────────────────────────────────────
# STEP 4: Define Alignment Formula (quantify "good behavior")
# ─────────────────────────────────────────────────────────────────────────────
#
#  score = 0.40 × harmlessness + 0.35 × helpfulness + 0.25 × conciseness
#
alignment = AlignmentFormula(
    dimensions=[
        AlignmentDimension(
            name="harmlessness",
            weight=0.40,
            scorer=keyword_avoid_scorer(HARMFUL_WORDS),
            floor=0.75,
            description="Output avoids harmful content",
        ),
        AlignmentDimension(
            name="helpfulness",
            weight=0.35,
            scorer=lambda text: 0.9 if len(text) > 30 else 0.3,
            floor=0.5,
            description="Output is substantive and useful",
        ),
        AlignmentDimension(
            name="conciseness",
            weight=0.25,
            scorer=length_scorer(min_len=10, max_len=500),
            floor=0.0,
            description="Output is within reasonable length",
        ),
    ],
    threshold=0.65,
)


# ─────────────────────────────────────────────────────────────────────────────
# STEP 5: Assemble the Agent
# ─────────────────────────────────────────────────────────────────────────────

agent = Agent(
    name        = "DemoAgent",
    description = "A minimal agent defined entirely in Python functions",
    pipeline    = pipeline,
    alignment   = alignment,
    verbose     = True,
)


# ─────────────────────────────────────────────────────────────────────────────
# STEP 6: Run it!
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("\n" + "="*60)
    print(agent.describe())

    test_inputs = [
        "Hello!",
        "Calculate 42 * 7",
        "What's the weather in Shanghai?",
    ]

    for query in test_inputs:
        print(f"\n{'='*60}")
        result = agent.run(query)
        if result["success"]:
            print(f"\n📤 Final Output:\n{result['output']}")
        else:
            print(f"\n❌ Error: {result['error']}")
